#include <iostream>

#include "cppns/archive/FileArchive.h"
#include "cppns/archive/PathArchive.h"

#include "cppns/util/Paths.h"

//TODO: global test, autogenerated, that calls other tests
EXPORTC int run() {

    try {
        CPathArchive path(gExecutablePath);
        path << "hello";
        path << "input.dat";

        std::cout << path.get() << std::endl;
        std::cout << path.getFilename() << std::endl;

        {
            CFileArchive<EOpenType::BINARY_WRITE> fileArchive(path);

            const size_t v = 5;
            fileArchive << v;
            fileArchive << "test";
            fileArchive << "test200";
        }

        {
            CFileArchive<EOpenType::BINARY_READ> fileArchive(path);

            size_t v;
            fileArchive >> v;
            std::string s;
            fileArchive >> s;
            std::string s2;
            fileArchive >> s2;

            std::cout << v << std::endl;
            std::cout << s << std::endl;
            std::cout << s2 << std::endl;

            CHashArchive hasher;
            hasher << v;
            hasher << s;
            hasher << s2;

            std::cout << "Hash: " << hasher.get() << std::endl;
        }
    } catch (Error::File::OpenException& fileOpenException) {
        std::cout << "Could not open file: " << fileOpenException.what() << std::endl;
        std::cout << "Please make sure the file exists and has the right permissions" << std::endl;
    }

    return 0;
}
