#include <iostream>

#include "cppns/archive/FileArchive.h"
#include "cppns/archive/PathArchive.h"

#include "cppns/util/Paths.h"

//TODO: global test, autogenerated, that calls other tests
cppns_main() {

        CPathArchive path(gExecutablePath);

        assert(!path.get().empty());

        path << "input.dat";

        std::cout << path.get() << std::endl;
        std::cout << path.getFilename() << std::endl;

        {
            CFileArchive<EOpenType::BINARY_WRITE> fileArchive(path);

            const size_t v = 5;
            fileArchive << v;
            fileArchive << "test";
            fileArchive << "test200";
        }

        assert(std::filesystem::exists(path.get()));

        {
            CFileArchive<EOpenType::BINARY_READ> fileArchive(path);

            size_t v;
            fileArchive >> v;
            std::string s;
            fileArchive >> s;
            std::string s2;
            fileArchive >> s2;

            std::cout << v << std::endl;
            std::cout << s << std::endl;
            std::cout << s2 << std::endl;

            assert(v == 5 && s == "test" && s2 == "test200");

            CHashArchive hasher;
            hasher << v;
            hasher << s;
            hasher << s2;

            CHashArchive hasher2;
            hasher2 << v;
            hasher2 << s;
            hasher2 << s2;

            std::cout << "Hash: " << hasher.get() << std::endl;

            assert(hasher.get() != 0 && hasher2.get() != 0);
            assert(hasher.get() == hasher2.get());
        }

    return 0;
}
