name: Multiplatform CMake Run

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    name: c++${{ matrix.cxx_standard }}-${{ matrix.platform.name }}-${{ matrix.platform.compiler }}-${{ matrix.platform.arch }}-cmake-run
    runs-on: ${{ matrix.platform.os }}
    env:
      vcpkgCommitId: 'a42af01b72c28a8e1d7b48107b33e4f286a55ef6'
      VCPKG_DEFAULT_TRIPLET: ${{ matrix.platform.triplet }}
    strategy:
      fail-fast: false
      matrix:
        cxx_standard:
          - 20
          - 23

        platform:
          - { arch: x64, triplet: x64-linux, name: linux, os: ubuntu-24.04, compiler: gcc, notest: false }
          - { arch: x64, triplet: x64-linux, name: linux, os: ubuntu-24.04, compiler: clang, notest: false }
          - { arch: x64, triplet: x64-osx, name: macos, os: macos-15, compiler: clang, notest: false }
          - { arch: x64, triplet: x64-windows, name: windows, os: windows-2022, compiler: msvc, notest: false }
          - { arch: x86, triplet: x86-windows, name: windows, os: windows-2022, compiler: msvc, notest: false }
          - { arch: arm64, triplet: arm64-windows, name: windows, os: windows-2022, compiler: msvc, notest: true }
          - { arch: x64, triplet: x64-mingw-dynamic, name: windows, os: windows-2022, compiler: mingw, notest: false }
    steps:
      # Checkout project, including submodules
      - uses: actions/checkout@v4
        with:
          submodules: true
      
      # Install latest CMake & Ninja
      - uses: lukka/get-cmake@latest
      
      # Optional: Setup vcpkg
      - name: Setup vcpkg
        uses: lukka/run-vcpkg@v11
        id: runvcpkg
        with:
          vcpkgDirectory: '${{ runner.workspace }}/b/vcpkg'
          vcpkgGitCommitId: '${{ env.vcpkgCommitId }}'
          vcpkgJsonGlob: '**/scripts/example_vcpkg.json'

      - name: Prints output of run-vcpkg's action
        run: echo "root='${{ steps.runvcpkg.outputs.RUNVCPKG_VCPKG_ROOT_OUT }}', triplet='${{ steps.runvcpkg.outputs.RUNVCPKG_VCPKG_DEFAULT_TRIPLET_OUT }}'"

        # Run CMake Build
      - name: Run CMake
        if: matrix.platform.arch != 'arm64'
        uses: lukka/run-cmake@v10
        with:
          configurePreset: 'ninja-multi-${{ matrix.platform.compiler }}-${{ matrix.platform.arch }}'
          configurePresetAdditionalArgs: "['-DCMAKE_CXX_STANDARD=${{ matrix.cxx_standard }}']"
          buildPreset: 'ninja-release-${{ matrix.platform.compiler }}-${{ matrix.platform.arch }}'
          testPreset: ${{ matrix.platform.notest && '' || format('test-release-{0}-{1}', matrix.platform.compiler, matrix.platform.arch) }}
