name: Multiplatform CMake Run

on: [push, pull_request]

jobs:
  build:
    name: ${{ matrix.os }}-${{ matrix.compiler }}-cmake-run
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        include:
          - os: ubuntu-24.04
            compiler: gcc

          - os: ubuntu-24.04
            compiler: clang

          - os: macos-15
            compiler: clang

          - os: windows-2022
            compiler: msvc

          - os: windows-2022
            compiler: mingw
    steps:
      # Checkout project, including submodules
      - uses: actions/checkout@v4
        with:
          submodules: true
      
      # Install latest CMake & Ninja
      - uses: lukka/get-cmake@latest
      
      # Optional: Setup vcpkg
      - name: Setup vcpkg
        uses: lukka/run-vcpkg@v11
        
        # Run CMake Build
      - name: Run CMake
        uses: lukka/run-cmake@v10
        with:
          configurePreset: 'ninja-multi-${{ matrix.compiler }}'
          buildPreset: 'ninja-release-${{ matrix.compiler }}'
          testPreset: 'test-${{ matrix.compiler }}-release'
